### ISSUE TITLE
whitespace handling

### ISSUE THREAD

**Issue by damianham** [TechMagister/liquid.cr#28]
Currently the whitespace feature of shopify liquid {%-   -%} seems like it is not supported in liquid.cr so generated artifacts have a lot of whitespace and many empty lines if  IF expressions are used within loops.

**Comment by TechMagister** [comment]
I guess you're talking about that feature : https://help.shopify.com/themes/liquid/basics/whitespace
I think it will require to update the parser : `src/liquid/parser.cr`

**Comment by docelic** [comment]
https://github.com/TechMagister/liquid.cr/pull/30
