### ISSUE TITLE
Add support for raw

### ISSUE THREAD

**Issue by faustinoaq** [TechMagister/liquid.cr#35]
Ref: https://shopify.github.io/liquid/tags/raw/

```liquid
{% raw %}
  In Handlebars, {{ this }} will be HTML-escaped, but
  {{{ that }}} will not.
{% endraw %}
```

On liquid.cr

```
Unhandled exception: Missing hash key: "raw" (KeyError)
  from /usr/lib/crystal/hash.cr:0:9 in 'fetch'
  from /usr/lib/crystal/hash.cr:62:5 in '[]'
  from lib/liquid/src/liquid/block_register.cr:10:5 in 'for_name'
  from lib/liquid/src/liquid/parser.cr:127:23 in 'consume_statement'
  from lib/liquid/src/liquid/parser.cr:55:11 in 'parse'
  from lib/liquid/src/liquid/parser.cr:22:7 in 'parse'
  from lib/liquid/src/liquid/template.cr:15:7 in 'parse'
  from src/testliquid.cr:17:1 in '__crystal_main'
  from /usr/lib/crystal/crystal/main.cr:104:5 in 'main_user_code'
  from /usr/lib/crystal/crystal/main.cr:93:7 in 'main'
  from /usr/lib/crystal/crystal/main.cr:133:3 in 'main'
  from __libc_start_main
  from _start
  from ???
```

**Comment by docelic** [comment]
Hey, good one, I'll try adding that tag. Thanks!

**Comment by docelic** [comment]
Hey @faustinoaq, {% raw %} should now be available in the current version of Liquid.cr.

In addition to the tag itself, the whitespace control has been made identical to original Liquid as well.
The behavior is as follows:
- The minus characters on the closing tag are ignored
- The minus characters in {%- raw -%} trim the whitespace before and/or after the raw..endraw tag, respectively.

Tests are included.

Please test in practice and report any problems. Thanks!
