### ISSUE TITLE
Active again?

### ISSUE THREAD

**Issue by anamba** [TechMagister/liquid.cr#45]
While attempting to update Amber today, I happened to notice that this repo is active again. Any interest in merging some (or all?) of the changes I made in my fork?

https://github.com/anamba/liquid.cr/blob/master/CHANGELOG.md

At this point, I am not using Crystal daily like I used to, so I am probably not going to find the time to break up the changes into individual PRs, but it would be nice not to have to maintain my own fork.

Especially now that Amber requires liquid 0.3.3, which means I now have to fork that, too (because my liquid fork is up to 0.6.0). Another case where crystal-lang/shards#299 would be really helpful.

**Comment by docelic** [comment]
Hey @anamba , this is great. I will go over your changes and extract/import the parts you have.
I will periodically update this ticket with the confirmation which parts were imported and/or which ones might need some discussion/coordination.
Thanks!
